### ISSUE TITLE
Prepare Library of components for Subutai Router

### ISSUE THREAD

**Issue by bkukanov** [subutai-io/subutai-router#1]
The Subutai Router 2.0 adds extra add-on features to SR 1.0, as well as it enhances the Ethernet Switch capability of SR 1.0 from Fast Ethernet to Gigabit Ethernet. We need to update the library and add component which are missing

**Comment by metinburak** [comment]
Done except Ethernet PHY TI DP83867IRRGZ, displayport Molex 47272000, RJ45 RJMG2012211A0FR and SATA 3 0678005005.

**Comment by bkukanov** [comment]
Displayport Molex 0472720001 has been added

**Comment by bkukanov** [comment]
Ethernet PHY TI DP83867IRRGZ, displayport Molex 0472720001 and SATA 3 0678005005 has been added

**Comment by bkukanov** [comment]
Done
