### ISSUE TITLE
TPM interface schematic capture

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#13]
The TPM interface as header will be added to the design with this issue.

**Comment by bkukanov** [comment]
Here information about TPM header's
https://superuser.com/questions/1216494/what-is-the-difference-between-various-tpm-modules
- ASUS TPM-M R2.0 (14 pin)  ->  TPM 2.0 compatible
- Asus TPM-L R2.0 (20 pin) ->  TPM 2.0 compatible
- Asus Trusted Platform Module TPM/FW3.19 (20 pins) -> TPM 1.2 compatible
- Gigabyte TPM Module GC-TPM2.0 (20 pins)

Asus header pinout http://forums.overclockers.com.au/threads/trusted-platform-module-asus-z170m-e-d3.1182000/
https://www.asus.com/support/FAQ/1006213/
![asus_tpm](https://user-images.githubusercontent.com/11937839/32156707-3391306e-bd69-11e7-97ce-850404b526b2.JPG)

**Comment by bkukanov** [comment]
I think it's better to use the header for 20 pin, because there is some compatibility with Asus TPM & Gigabit's TPM and in front of IO consumption there are same 20pin and 14pin

**Comment by bkukanov** [comment]
https://www.gigabyte.com/Motherboard/GC-TPM-rev-20#ov
http://download.gigabyte.ru/manual/mb_manual_ga-b250-hd3p_e.pdf
![image](https://user-images.githubusercontent.com/11937839/32316367-1140544a-bfda-11e7-9257-1e26eee9c57d.png)

**Comment by bkukanov** [comment]
done beside the eMMC header sheet
