### ISSUE TITLE
PS Gigabit Ethernet PHY schematic capture

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#14]
TI DP83867IRRGZ will be added to the schematic design with a RJ45 RJMG2012211A0FR connector.

**Comment by bkukanov** [comment]
TI DP83867IRRGZ added to sheet ETH, now need to connect RJ45 RJMG2012211A0FR connector

**Comment by bkukanov** [comment]
ETH-PHY sheet has been added with schematic design
