### ISSUE TITLE
SATA 3.0 Interface schematic capture

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#18]
1x SATA interface will be added to the schematic design with connector: 
Molex 0678005005

**Comment by metinburak** [comment]
@bkukanov  could u add this connector?

**Comment by metinburak** [comment]
I will add the clock synthesizer btw, u don't mess up with clock synthesizer.

**Comment by bkukanov** [comment]
SATA interface is added to sheet B505_clk
