### ISSUE TITLE
Generating the PL DDR4 controller's pinout in Vivado's latest (for Ultrascale)

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#22]
The #8  needs this in order to connect the DDR4 module sch to Zynq. We will create a new project with Vivado based on Ultrascale and get the pinout.

**Comment by metinburak** [comment]
@bkukanov we need this to route the PL SODIMM and also, any PL ios assigned so far in the pcb will be affected by this default pins generated by the PL ddr controller in vivado ultrazynq edition. What do u think?

**Comment by bkukanov** [comment]
ok @metinburak  will look into it

**Comment by bkukanov** [comment]
Here is the pin out of xczu3eg-sfvc784-1-i for DDR4 64bit SODIMM
[example_design_64bit.txt](https://github.com/subutai-io/subutai-router/files/1504894/example_design_64bit.txt)
![ddr4_64bit_sodimm](https://user-images.githubusercontent.com/11937839/33253868-f41f6e1a-d36f-11e7-8d87-d3273f402d8f.png)

**Comment by bkukanov** [comment]
here is pin out of xczu3eg-sfvc784-1-i for DDR4 72bit SODIMM
![ddr4_72bit_sodimm](https://user-images.githubusercontent.com/11937839/33253898-22e4f364-d370-11e7-9272-bca805ddf31a.png)
[example_design_72bit.txt](https://github.com/subutai-io/subutai-router/files/1504899/example_design_72bit.txt)
