### ISSUE TITLE
Raspberry Pi Expansion Schematic Capture

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#4]
The Raspberry Pi Expansion Circuit will be designed.

**Comment by metinburak** [comment]
Done, but the Sheet id will be written here.

**Comment by metinburak** [comment]
I can not understand where it is, i have added it before, @bkukanov  please could u add it?

**Comment by bkukanov** [comment]
![pi3_gpio](https://user-images.githubusercontent.com/11937839/33305345-f1a1e8e8-d437-11e7-8d73-62928e31f430.png)
Rasperry pi header was added

**Comment by bkukanov** [comment]
We need to modify the CAD file

**Comment by bkukanov** [comment]
It was added to design PMOD_ARD_RASP sheet
