### ISSUE TITLE
PL side DDR4 SODIMM schematic capture

### ISSUE THREAD

**Issue by metinburak** [subutai-io/subutai-router#8]
The PL side DDR4 circuit schematic design will be handled in this issue.

**Comment by metinburak** [comment]
#22 will get us the pinout with a Zynq Ultrascale+ project witha aPL DDR4 controller.

**Comment by metinburak** [comment]
PL DDR SODIMM module is in Sheet 15.

**Comment by bkukanov** [comment]
PL DDR SODIMM schematic PL_DDR4_SODIMM sheet
